#####################################################
# Taps (Third-party Repositories)                   #
#####################################################
# Homebrew
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"

#####################################################
# Brews (Packages)                                  #
#####################################################
# Tools/Utilities
brew "git"
brew "fish"
brew "neofetch"
brew "defaultbrowser"
brew "wallpaper"
brew "mas"
brew "jq"
# Development
brew "openjdk"
brew "mdv"
# Apperance
brew "bat"
brew "exa"
brew "tree"

#####################################################
# Casks (Applications)                              #
#####################################################
# Tools/Utilities
cask "kitty", args: { no_quarantine: true }
cask "notion", args: { no_quarantine: true }
cask "logitech-options", args: { no_quarantine: true }
cask "balenaetcher", args: { no_quarantine: true }
# Internet
cask "firefox", args: { no_quarantine: true }
cask "google-chrome", args: { no_quarantine: true }
cask "tor-browser", args: { no_quarantine: true }
# Gaming
cask "runelite", args: { no_quarantine: true }
cask "minecraft", args: { no_quarantine: true }
cask "steam", args: { no_quarantine: true }
cask "discord", args: { no_quarantine: true }
# Work
cask "microsoft-teams", args: { no_quarantine: true }
# Productivity
cask "zoom", args: { no_quarantine: true }
cask "numi", args: { no_quarantine: true }
# Content Creation
cask "adobe-creative-cloud", args: { no_quarantine: true }
cask "processing", args: { no_quarantine: true }
# Virtualization
cask "parallels", args: { no_quarantine: true } 
# Development
cask "eclipse-java", args: { no_quarantine: true }
# Window Manager
cask "amethyst", args: { no_quarantine: true }

#####################################################
# Mac App Store                                     #
#####################################################
# Tools/Utilities
mas "bitwarden", id: 1352778147
# Productivity
mas "iA Writer", id: 775737590
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838

#####################################################
# System Fonts                                      #
#####################################################
# Used in: .spaceebarrc & kitty.conf
cask "font-meslo-lg-nerd-font"
